id: opecha:P000806
initial_creation_type: ocr
source_metadata:
  id: bdr:W21939
  title: རྙིང་མ་རྒྱུད་འབུམ། （སྡེ་དགེ་པར་མ།）
  volumes:
    ccbaf2ef18b849ac8123c6a932a422b0:
      image_group_id: I6321
      title: ''
      base_file: v001.txt
    376ab8b5191542b8ba8417ec708bda52:
      image_group_id: I6322
      title: ''
      base_file: v002.txt
    566740e89f2c4bcfb90a199b7c9fda9e:
      image_group_id: I6323
      title: ''
      base_file: v003.txt
    78318db48bc54e6aa8e0bc6c74186dda:
      image_group_id: I6324
      title: ''
      base_file: v004.txt
    a277198ff9ec4551bca05d8b78500747:
      image_group_id: I6325
      title: ''
      base_file: v005.txt
    ae08303c73f74165bad2b76a616d0631:
      image_group_id: I6326
      title: ''
      base_file: v006.txt
    046af9c8762849aaa64b521e7baf8a4b:
      image_group_id: I6327
      title: ''
      base_file: v007.txt
    e5202400bdc4477e8ea1c262500ad72f:
      image_group_id: I6328
      title: ''
      base_file: v008.txt
    81bcb99f8de243d7906cf5a964812410:
      image_group_id: I6329
      title: ''
      base_file: v009.txt
    e0284f72a7a64318a56b9728bf804a2c:
      image_group_id: I6330
      title: ''
      base_file: v010.txt
    5dea8cc9938d4bc1b97e021751f2e03a:
      image_group_id: I6331
      title: ''
      base_file: v011.txt
    8e90ebc6161b479c9d8e6ca649a5d4cd:
      image_group_id: I6332
      title: ''
      base_file: v012.txt
    0ffbbf3b8405472399a434c9081dce23:
      image_group_id: I6333
      title: ''
      base_file: v013.txt
    80caff3f2010461f9e4489b14e8c5cff:
      image_group_id: I6334
      title: ''
      base_file: v014.txt
    ba313e926ca249fea844d766a8e25bd6:
      image_group_id: I6335
      title: ''
      base_file: v015.txt
    aca1271debbf49fab8b56148410a6476:
      image_group_id: I6336
      title: ''
      base_file: v016.txt
    0cfcc8a6e4054719821fd54032d7a2c8:
      image_group_id: I6337
      title: ''
      base_file: v017.txt
    2ff8d522ff784b0a957337d8e1983a01:
      image_group_id: I6338
      title: ''
      base_file: v018.txt
    1a63eae889fd4363a84573c9cf811d00:
      image_group_id: I6339
      title: ''
      base_file: v019.txt
    69077396f35b43ad99daaccc7453a3aa:
      image_group_id: I6340
      title: ''
      base_file: v020.txt
    8e134091f09f4daca7a348c7a68cedac:
      image_group_id: I6341
      title: ''
      base_file: v021.txt
    822c8487f4e14513a7ded522882ee966:
      image_group_id: I6342
      title: ''
      base_file: v022.txt
    a822e12ed1e84048b663962de198d4ea:
      image_group_id: I6343
      title: ''
      base_file: v023.txt
    c86c8a14835e4a749ce536ef07dcf37f:
      image_group_id: I6344
      title: ''
      base_file: v024.txt
    de7d4ab7fbea49f99b1c9343fef22828:
      image_group_id: I6345
      title: ''
      base_file: v025.txt
    0cd68eabf9fc4c6197770992091118fe:
      image_group_id: I6346
      title: ''
      base_file: v026.txt
  author: ''
