id: IAB4BBFF0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-02T04:29:00+00:00'
last_modified: '2022-06-13T12:45:36.927207+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21939
  title: རྙིང་མ་རྒྱུད་འབུམ། （སྡེ་དགེ་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0C19:
      image_group_id: I6321
      title: ''
      total_pages: ''
      order: 1
      base_file: 0C19.txt
    613A:
      image_group_id: I6322
      title: ''
      total_pages: ''
      order: 2
      base_file: 613A.txt
    0ED4:
      image_group_id: I6323
      title: ''
      total_pages: ''
      order: 3
      base_file: 0ED4.txt
    E4AE:
      image_group_id: I6324
      title: ''
      total_pages: ''
      order: 4
      base_file: E4AE.txt
    2C0E:
      image_group_id: I6325
      title: ''
      total_pages: ''
      order: 5
      base_file: 2C0E.txt
    4A90:
      image_group_id: I6326
      title: ''
      total_pages: ''
      order: 6
      base_file: 4A90.txt
    4BA6:
      image_group_id: I6327
      title: ''
      total_pages: ''
      order: 7
      base_file: 4BA6.txt
    9B42:
      image_group_id: I6328
      title: ''
      total_pages: ''
      order: 8
      base_file: 9B42.txt
    8E99:
      image_group_id: I6329
      title: ''
      total_pages: ''
      order: 9
      base_file: 8E99.txt
    '3244':
      image_group_id: I6330
      title: ''
      total_pages: ''
      order: 10
      base_file: 3244.txt
    '9109':
      image_group_id: I6331
      title: ''
      total_pages: ''
      order: 11
      base_file: 9109.txt
    '8600':
      image_group_id: I6332
      title: ''
      total_pages: ''
      order: 12
      base_file: 8600.txt
    ECA1:
      image_group_id: I6333
      title: ''
      total_pages: ''
      order: 13
      base_file: ECA1.txt
    '9197':
      image_group_id: I6334
      title: ''
      total_pages: ''
      order: 14
      base_file: 9197.txt
    4C32:
      image_group_id: I6335
      title: ''
      total_pages: ''
      order: 15
      base_file: 4C32.txt
    3DED:
      image_group_id: I6336
      title: ''
      total_pages: ''
      order: 16
      base_file: 3DED.txt
    '9089':
      image_group_id: I6337
      title: ''
      total_pages: ''
      order: 17
      base_file: 9089.txt
    0977:
      image_group_id: I6338
      title: ''
      total_pages: ''
      order: 18
      base_file: 0977.txt
    B134:
      image_group_id: I6339
      title: ''
      total_pages: ''
      order: 19
      base_file: B134.txt
    846F:
      image_group_id: I6340
      title: ''
      total_pages: ''
      order: 20
      base_file: 846F.txt
    '9961':
      image_group_id: I6341
      title: ''
      total_pages: ''
      order: 21
      base_file: 9961.txt
    B4FF:
      image_group_id: I6342
      title: ''
      total_pages: ''
      order: 22
      base_file: B4FF.txt
    '7995':
      image_group_id: I6343
      title: ''
      total_pages: ''
      order: 23
      base_file: 7995.txt
    '7164':
      image_group_id: I6344
      title: ''
      total_pages: ''
      order: 24
      base_file: 7164.txt
    '9494':
      image_group_id: I6345
      title: ''
      total_pages: ''
      order: 25
      base_file: 9494.txt
    423E:
      image_group_id: I6346
      title: ''
      total_pages: ''
      order: 26
      base_file: 423E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
